# .streamlit/secrets.toml

openai_api_key = "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"

google_sheet_id = "1z7vTglgaA2R6AiJcSRc-wWQDJwJrJj0TWWhKNCHrx7Y"  # this is your existing Sheet ID

mailjet_api_key = "0605fe01a4ce3f636d04ade9efc66528"
mailjet_secret_key = "3a672b77d6124142eba187f95402b0dc"

email_to = "jordan@your-agency.ca"
email_from = "jordan@your-agency.ca"
smtp_server = "in-v3.mailjet.com"
smtp_port = 587

credentials_path = "C:/Users/Jordan/Desktop/credentials.json"
